language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

install:
  - travis_retry pip install -r dev-requirements.txt
  - travis_retry pip install -r contrib-requirements.txt

before_script: flake8 .

script: py.test --tb short
